[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SafeGPT"
authors = [{name = "Trinity", email = "help@trinityagi.com"}]
dynamic = ["version", "description"]
